# Generated by Django 4.2 on 2023-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("men", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="games_played",
            field=models.IntegerField(default=0),
        ),
    ]
