# Generated by Django 4.2 on 2023-04-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("men", "0003_delete_gameplayed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="games_played",
        ),
    ]
