# Generated by Django 4.2 on 2023-04-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("men", "0004_remove_team_games_played"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SelectTeamCategory",
        ),
    ]
