# Generated by Django 4.2 on 2023-04-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("men", "0005_delete_selectteamcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Points",
        ),
    ]
