# Generated by Django 4.2 on 2023-04-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("men", "0006_delete_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="division",
            field=models.CharField(
                choices=[("KBF", "KBF"), ("DIV1", "DIV1"), ("DIV2", "DIV2")],
                default=1,
                max_length=4,
            ),
            preserve_default=False,
        ),
    ]
